apiVersion: v1
kind: Secret
metadata:
  name: db2-secret
  namespace: project-plato
type: Opaque
data:
  username: YWRtaW4=  # "admin" in base64
  password: U3VwZXJTZWNyZXQxMjM=  # "SuperSecret123" in base64
